// ============================================================
// Bundled child-voice pack (Option B: pre-made AI child voice).
//
// This maps normalized text -> a bundled audio asset generated OFFLINE from a
// licensed pre-made child voice (e.g. an ElevenLabs kid voice). The app plays
// these clips instead of on-device TTS whenever a match exists, and falls back
// to TTS otherwise.
//
// IMPORTANT:
//   • No API key ships in the app. Clips are generated at build time by
//     scripts/generate-voice-pack.mjs and committed as assets here.
//   • This file is regenerated by that script. The empty default below is safe:
//     with no clips, the app simply uses TTS everywhere (current behavior).
//   • Only ship audio you are licensed to distribute (see the script header).
//
// Keys are produced by voiceKey() so lookups are consistent (lowercase,
// trimmed, spaces -> underscores). Letters are stored as single characters.
// ============================================================

/**
 * The generated pack. Each value is a React Native asset module id
 * (the result of `require("./clips/apple.mp3")`).
 *
 * Example after generation:
 *   export const VOICE_PACK: Record<string, number> = {
 *     "a": require("./clips/letter_a.mp3"),
 *     "apple": require("./clips/apple.mp3"),
 *     "welcome": require("./clips/welcome.mp3"),
 *   };
 */
export const VOICE_PACK: Record<string, number> = {};

/** Normalize any text into a stable lookup key. */
export function voiceKey(text: string): string {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "") // drop punctuation
    .replace(/\s+/g, "_");
}

/** Returns the bundled asset for a piece of text, or null if not in the pack. */
export function voiceClip(text: string): number | null {
  const key = voiceKey(text);
  return VOICE_PACK[key] ?? null;
}

/** Whether the pack currently contains any clips. */
export function hasVoicePack(): boolean {
  return Object.keys(VOICE_PACK).length > 0;
}
